apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ryr-prod
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: 'remy.greinhofer@gmail.com'
    privateKeySecretRef:
      name: ryr-prod
    http01: {}
